# Generated by Django 3.2.4 on 2021-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
